[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

build_flags = 
    -D USBCON
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_HID
    -D ENABLE_HWSERIAL2
    -D USBD_VID=0x0483
    -D USBD_PID=0x5711
    -D USB_PRODUCT=\"ESP_Touchpad_HID\"
